// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

import 'package:narrata/core/config/env_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: EnvConfig.androidApiKey,
    appId: EnvConfig.androidAppId,
    messagingSenderId: EnvConfig.messagingSenderId,
    projectId: EnvConfig.projectId,
    storageBucket: EnvConfig.storageBucket,
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: EnvConfig.iosApiKey,
    appId: EnvConfig.iosAppId,
    messagingSenderId: EnvConfig.messagingSenderId,
    projectId: EnvConfig.projectId,
    storageBucket: EnvConfig.storageBucket,
    iosBundleId: EnvConfig.iosBundleId,
  );
}
